import React from "react";
import "./style.scss";
const OurValues = () => {
  return (
    <div className="our-values">
      <div className="our-values-title">
        <h1>About E-learning</h1>
      </div>
      <div className="our-values-items">
        <div className="our-values-item">
          {/* <h1>About E-Learning</h1> */}
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nullam vehicula ipsum a arcu cursus vitae congue. Nunc vel risus commodo viverra maecenas accumsan. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Pharetra pharetra massa massa ultricies mi quis hendrerit. Quis blandit turpis cursus in hac. Enim facilisis gravida neque convallis a cras semper auctor. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Tellus molestie nunc non blandit massa enim nec dui. Arcu non sodales neque sodales. Turpis egestas maecenas pharetra convallis posuere morbi leo urna. Dictum sit amet justo donec. Arcu felis bibendum ut tristique et egestas. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Id cursus metus aliquam eleifend mi in. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero</p>
          <p>Risus in hendrerit gravida rutrum quisque non. Duis ut diam quam nulla. Nisl nunc mi ipsum faucibus. Imperdiet dui accumsan sit amet. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Sit amet cursus sit amet dictum sit amet justo. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna. Cursus metus aliquam eleifend mi in. Erat velit scelerisque in dictum non consectetur a. Quis viverra nibh cras pulvinar mattis nunc sed.</p>
          <p>Et netus et malesuada fames ac turpis egestas integer. Commodo elit at imperdiet dui accumsan. Ultrices eros in cursus turpis. Enim nunc faucibus a pellentesque sit amet porttitor eget. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Euismod nisi porta lorem mollis aliquam ut porttitor. In est ante in nibh mauris. Sed odio morbi quis commodo odio aenean sed. Morbi tempus iaculis urna id volutpat. Lorem ipsum dolor sit amet consectetur adipiscing elit. Tristique sollicitudin nibh sit amet. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh sed. Quis eleifend quam adipiscing vitae proin. Eu lobortis elementum nibh tellus molestie nunc. Quis varius quam quisque id diam vel quam elementum pulvinar. Tempus urna et pharetra pharetra massa massa ultricies. Aliquam ut porttitor leo a diam sollicitudin.</p>
          <p>Et netus et malesuada fames ac turpis egestas integer. Commodo elit at imperdiet dui accumsan. Ultrices eros in cursus turpis. Enim nunc faucibus a pellentesque sit amet porttitor eget. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Euismod nisi porta lorem mollis aliquam ut porttitor. In est ante in nibh mauris. Sed odio morbi quis commodo odio aenean sed. Morbi tempus iaculis urna id volutpat. Lorem ipsum dolor sit amet consectetur adipiscing elit. Tristique sollicitudin nibh sit amet. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh sed. Quis eleifend quam adipiscing vitae proin. Eu lobortis elementum nibh tellus molestie nunc. Quis varius quam quisque id diam vel quam elementum pulvinar. Tempus urna et pharetra pharetra massa massa ultricies. Aliquam ut porttitor leo a diam sollicitudin.</p>
          <p>Et netus et malesuada fames ac turpis egestas integer. Commodo elit at imperdiet dui accumsan. Ultrices eros in cursus turpis. Enim nunc faucibus a pellentesque sit amet porttitor eget. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Euismod nisi porta lorem mollis aliquam ut porttitor. In est ante in nibh mauris. Sed odio morbi quis commodo odio aenean sed. Morbi tempus iaculis urna id volutpat. Lorem ipsum dolor sit amet consectetur adipiscing elit. Tristique sollicitudin nibh sit amet. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh sed. Quis eleifend quam adipiscing vitae proin. Eu lobortis elementum nibh tellus molestie nunc. Quis varius quam quisque id diam vel quam elementum pulvinar. Tempus urna et pharetra pharetra massa massa ultricies. Aliquam ut porttitor leo a diam sollicitudin.</p>
        </div>
        {/* <div className="our-values-item">
          <h1>About E-Learning</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nullam vehicula ipsum a arcu cursus vitae congue. Nunc vel risus commodo viverra maecenas accumsan. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Pharetra pharetra massa massa ultricies mi quis hendrerit. Quis blandit turpis cursus in hac. Enim facilisis gravida neque convallis a cras semper auctor. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Tellus molestie nunc non blandit massa enim nec dui. Arcu non sodales neque sodales. Turpis egestas maecenas pharetra convallis posuere morbi leo urna. Dictum sit amet justo donec. Arcu felis bibendum ut tristique et egestas. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Id cursus metus aliquam eleifend mi in. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero</p>
          <p>Risus in hendrerit gravida rutrum quisque non. Duis ut diam quam nulla. Nisl nunc mi ipsum faucibus. Imperdiet dui accumsan sit amet. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Sit amet cursus sit amet dictum sit amet justo. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna. Cursus metus aliquam eleifend mi in. Erat velit scelerisque in dictum non consectetur a. Quis viverra nibh cras pulvinar mattis nunc sed.</p>
          <p>Et netus et malesuada fames ac turpis egestas integer. Commodo elit at imperdiet dui accumsan. Ultrices eros in cursus turpis. Enim nunc faucibus a pellentesque sit amet porttitor eget. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Euismod nisi porta lorem mollis aliquam ut porttitor. In est ante in nibh mauris. Sed odio morbi quis commodo odio aenean sed. Morbi tempus iaculis urna id volutpat. Lorem ipsum dolor sit amet consectetur adipiscing elit. Tristique sollicitudin nibh sit amet. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh sed. Quis eleifend quam adipiscing vitae proin. Eu lobortis elementum nibh tellus molestie nunc. Quis varius quam quisque id diam vel quam elementum pulvinar. Tempus urna et pharetra pharetra massa massa ultricies. Aliquam ut porttitor leo a diam sollicitudin.</p>
        </div> */}
      </div>
    </div>
  );
};

export default OurValues;
